import 'dotenv/config';
export const DOMAIN = process.env.NEXT_PUBLIC_DOMAIN;
export const MODULEMOVIE = process.env.NEXT_PUBLIC_MODULEMOVIE;
export const MODULEAUTH = process.env.NEXT_PUBLIC_MODULEAUTH;
export const MODULEUSER = process.env.NEXT_PUBLIC_MODULEUSER;
export const MODULECINEMA = process.env.NEXT_PUBLIC_MODULECINEMA
export const GETMOVIE = process.env.NEXT_PUBLIC_GETMOVIE;
export const ACCESS_TOKEN = process.env.NEXT_PUBLIC_ACCESS_TOKEN;
export const GETDETAILMOVIE = process.env.NEXT_PUBLIC_GETDETAILMOVIE
export const ADDMOVIE = process.env.NEXT_PUBLIC_ADDMOVIE
export const DELETEMOVIE = process.env.NEXT_PUBLIC_DELETEMOVIE
export const GETLISTBANNER = process.env.NEXT_PUBLIC_GETLISTBANNER
export const REGISTER = process.env.NEXT_PUBLIC_REGISTER
export const LOGIN = process.env.NEXT_PUBLIC_LOGIN
export const GETALLUSER = process.env.NEXT_PUBLIC_GETALLUSER
export const ADDUSER = process.env.NEXT_PUBLIC_ADDUSER
export const DELETEUSER = process.env.NEXT_PUBLIC_DELETEUSER
export const UPDATEUSER = process.env.NEXT_PUBLIC_UPDATEUSER
export const SEARCHUSER = process.env.NEXT_PUBLIC_SEARCHUSER
export const GETCINEMASYSTEM = process.env.NEXT_PUBLIC_GETCINEMASYSTEM
export const GETCINEMACLUSTER = process.env.NEXT_PUBLIC_GETCINEMACLUSTER
export const GETSHOWTIMEBYCINEMACLUSTER = process.env.NEXT_PUBLIC_GETSHOWTIMEBYCINEMACLUSTER
export const GETSHOWTIMEBYMOVIE = process.env.NEXT_PUBLIC_GETSHOWTIMEBYMOVIE
export const ADDCINEMASYSTEM = process.env.NEXT_PUBLIC_ADDCINEMASYSTEM
export const ADDCINEMACLUSTER = process.env.NEXT_PUBLIC_ADDCINEMACLUSTER
export const DELETECINEMACLUSTER = process.env.NEXT_PUBLIC_DELETECINEMACLUSTER


